deployment:
  tasks:
    # Backend: Copy files (DO NOT DELETE, to keep .env and uploads safe)
    - echo "==> Deploying Backend (api to office-backend-folder/api)"
    # - mkdir -p /home2/roshande/office-backend-folder/api
    - cp -r ${PWD}/api/* /home2/roshande/office-backend-folder/api/

    # Backend: Laravel install & optimize
    - cd /home2/roshande/office-backend-folder/api
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # Frontend: Copy built files to live folder (no delete!)
    - echo "==> Deploying Frontend (frontend/app to office.roshandevkota.com.np)"
    - cp -r ${PWD}/frontend/app/* /home2/roshande/office.roshandevkota.com.np/
