---
deployment:
  tasks:
    # Frontend: Deploy
    - echo "==== DEPLOYING FRONTEND ===="
    - cp -ru /home2/roshande/office-deploy-source/frontend/out/* /home2/roshande/office.roshandevkota.com.np/

    # Backend: Deploy
    - echo "==== DEPLOYING BACKEND ===="
    - cp -ru /home2/roshande/office-deploy-source/api/* /home2/roshande/api/

    # Laravel optimize (no composer!)
    - cd /home2/roshande/api
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
